### ISSUE TITLE
Make fast-eslint work with other eslint-config modules

### ISSUE THREAD

**Issue by radubrehar** [Adezandee/fast-eslint#103]
Is there a way to make it work with other eslint-config files?

**Comment by radubrehar** [comment]
eg: i've just published `eslint-config-zippyui` and want to make it work with it

**Comment by radubrehar** [comment]
Initially I believed I should have installed my eslint-config globally, but that didn't help either. Running `eslint` from an npm script with my custom config works, but fast-eslint won't pick it up.

**Comment by Adezandee** [comment]
Hi @radubrehar,
Yeah, due to recent change in how `eslint` loads its dependencies, monkey patching `require` to load atom current project's `node_modules` doesn't work anymore. ATM their is no parameter for internal `CLIEngine` to indicate a custom dependencies location (regardless of execution dir). It's a bit convoluted but for it to work you have to `npm install` your config inside `~/.atom/packages/fast-eslint` for now...

**Comment by radubrehar** [comment]
@Adezandee thanks for the solution, it worked as expected!
