### ISSUE TITLE
Unable to use custom eslint-config package

### ISSUE THREAD

**Issue by stalniy** [Adezandee/fast-eslint#111]
I use custom eslint config package: https://github.com/concrete-cc/eslint-config-concrete-base

```json
{
  "extends": "concrete-base",
  "parser": "babel-eslint",
  "globals": {
    "IS_PRODUCTION": true
  },
  "rules": {
    "no-return-assign": 0
  },
  "settings": {
    "import/resolver": "webpack"
  }
}
```

And fast-eslint shows me package not found

**Comment by Adezandee** [comment]
Hi @stalniy, thx for your feedback. Back in ESLint `2.8.0`, this wasn't possible due to the way eslint loads his configuration files. With recent version, they changed their loading logic and I'm able to hook on this again.
Due to version compatibility, `fast-eslint` will load in priority packages available internally, then inside your current project `node_modules` then inside global npm lib if its available (this last might be clunky, I didn't test long).

I'll release a new version in few minutes.

**Comment by Adezandee** [comment]
@stalniy please try with latest version and let me know 👍
