### ISSUE TITLE
.eslintignore is not read

### ISSUE THREAD

**Issue by angelathewebdev** [Adezandee/fast-eslint#47]
I have an `.eslintignore` in my project root folder, and when I open files that belongs in the ignore path, `fast-eslint` go ahead and performed lint regardless.

The plugin seems to accept the configuration in my `.eslintrc` file without a problem. So, I'm wondering if I'm missing some kind of configuration

**Comment by Adezandee** [comment]
Hi @angelathewebdev, thanks for your feedback.
Indeed `.eslintignore` files were not read by the `CLIEngine`. I've done a fix to make them works just like `.gitignore` files works. It's slightly different from default behavior because at the moment, `eslint` only take into account the "current working directory" `.eslintignore` (see [Ignoring Files and Directories](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories)), but this notion is not really present in the context of Atom.
There is no merging logic, the first file found in the directory hierarchy is picked up and read.
